### ISSUE TITLE
Fix tests after migration to ktlint 1.0

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1737]
All tests marked as `@Disabled("https://github.com/saveourtool/diktat/issues/1737")`

Some of them can fail is due to multiply runs, another -- due to modification of AST tree (limitation of kotlin 1.9):
```
java.lang.IllegalArgumentException: Missing extension point: org.jetbrains.kotlin.com.intellij.treeCopyHandler in container {}
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:250) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.encodeInformation(ChangeUtil.java:43) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.lambda$encodeInformation$0(ChangeUtil.java:39) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.encodeInformation(ChangeUtil.java:39) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:95) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:87) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.copyElement(TreeElement.java:58) ~[kotlin-compiler-embeddable-1.9.10.jar:1.9.10-release-459]
	at com.saveourtool.diktat.ruleset.rules.chapter6.classes.StatelessClassesRule$handleClass$1.invoke(StatelessClassesRule.kt:56) ~[main/:?]
	at com.saveourtool.diktat.ruleset.rules.chapter6.classes.StatelessClassesRule$handleClass$1.invoke(StatelessClassesRule.kt:51) ~[main/:?]
	at com.saveourtool.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:273) ~[main/:?]
```

Possible solutions: https://github.com/pinterest/ktlint/pull/2044

**Comment by nulls** [comment]
Ignored tests:
`IndentationRuleTestSuite / JUnit Jupiter / IndentationRuleFixTest`
- `indentation rule - example 1`

`IdentifierNamingFixTest`
- `incorrect object name fix`
- `incorrect class name fix`
- `incorrect variable name case fix`

`KdocCommentsFixTest`
- `check fix without class kdoc`

`KdocMethodsFixTest`
- `@param tag should be added to existing KDoc`

`KdocMethods rule should reformat code (full example)`
- `@throws tag should be added to existing KDoc`

`BracesRuleFixTest`
- `should add braces to do-while loops with empty body`
- `should add braces to if-else statements - 1`

`FileStructureRuleTest`
- `check by #4 should trigger`

`LineLengthFixTest`
- `shouldn't fix`
- `should fix short long right value`
- `should fix complex long binary expressions`
- `fix long Dot Qualified Expression`
- `should fix annotation`
- `should fix long string template while some fix is already done`
- `should fix long binary expression`
- `should fix long right value`
- `should fix long comment`
- `should not fix long comment which located on the line length limit`
- `should fix long function`

`LocalVariablesWarnTest`
- `need to allow declaring vars outside of loops`
- `local variables defined in outer scope and used in several scopes`
- `local variables defined in outer scope and used only in nested scope`
- `need to allow declaring vars outside collection methods`
- `should check variables initialized with constructor with no parameters`

`NewlinesRuleWarnTest`
- `long argument list should be split into several lines`

`IndentationRuleFixTest`
- `indentation rule - example 1`

`SmartCastRuleWarnTest`
- `smart cast in when bad`

`ExtensionFunctionsSameNameWarnTest`
- `should trigger on classes in other files`

`RulesConfigValidationTest`
- `should throw error on invalid configuration section`

`VariablesWithAssignmentsSearchTest`
- `testing proper variables search with lambda`

`VariablesWithUsagesSearchTest`
- `testing proper variables search in class with the property in the end`
- `testing proper variables search in companion object`
- `testing proper variables search in function with a class nested in a function`
- `testing proper variables search in companion object with less priority then property`
